# -*- coding: utf-8 -*-
"""
Created on Tue Jan 01 11:38:07 2019
@author: Kevin Gomez (Masel Lab)
file processes data generated by matlab simulations for use in figures
"""

import pickle
import scipy as sp
import numpy as np
import copy as cpy

# basic functions needed for processing data
# -----------------------------------------------------------------------------
def indx_2_arry_map(indx,N):
    
    return []

# read matlab outputs and create python data for figure using grand means
# -----------------------------------------------------------------------------

cd ~/Documents/mutBiasCI/data/

data_file=open('mutBiasCI_data_all_simulation_grand_means_ml-01-1.dat')
grand_means = data_file.read().splitlines()
data_file.close()
data_file=open('mutBiasCI_data_all_simulation_parameters_ml-01-0.dat')
parameters = data_file.read().splitlines()
data_file.close()
del data_file

num_of_sims = len(grand_means)     # number of simulations
for i in range(num_of_sims):
    grand_means[i]='grand_means[i]=np.array(['+grand_means[i].replace('\t',',')+'])'
    exec(grand_means[i])
    parameters[i]='parameters[i]=np.array([['+parameters[i].replace('\t',',')+']])'
    exec(parameters[i])
    
# reconstruct array of parameters 
arry_dim = int(0.5*(np.sqrt(8*num_of_sims+1)-1))
sarry = np.zeros([arry_dim, 1])
Uarry = np.zeros([arry_dim, 1])

for i in range(arry_dim):
    sarry[ =     
    for j in range(arry_dim-i):
        

    
    